/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteSlugRouteImport } from './routes/invite.$slug'
import { Route as LayoutTemplatesRouteImport } from './routes/_layout/templates'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutEventsRouteImport } from './routes/_layout/events'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutBillingRouteImport } from './routes/_layout/billing'
import { Route as LayoutAssistantRouteImport } from './routes/_layout/assistant'
import { Route as LayoutEventsIndexRouteImport } from './routes/_layout/events/index'
import { Route as LayoutEventsNewRouteImport } from './routes/_layout/events/new'
import { Route as LayoutEventsEventIdRouteImport } from './routes/_layout/events/$eventId'
import { Route as LayoutAdminPaymentsRouteImport } from './routes/_layout/admin/payments'
import { Route as LayoutEventsEventIdIndexRouteImport } from './routes/_layout/events/$eventId/index'
import { Route as LayoutEventsEventIdSettingsRouteImport } from './routes/_layout/events/$eventId/settings'
import { Route as LayoutEventsEventIdInvitationsRouteImport } from './routes/_layout/events/$eventId/invitations'
import { Route as LayoutEventsEventIdAnalyticsRouteImport } from './routes/_layout/events/$eventId/analytics'
import { Route as LayoutEventsEventIdGuestsIndexRouteImport } from './routes/_layout/events/$eventId/guests.index'
import { Route as LayoutEventsEventIdGuestsNewRouteImport } from './routes/_layout/events/$eventId/guests.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteSlugRoute = InviteSlugRouteImport.update({
  id: '/invite/$slug',
  path: '/invite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTemplatesRoute = LayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsRoute = LayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBillingRoute = LayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAssistantRoute = LayoutAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsIndexRoute = LayoutEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutEventsNewRoute = LayoutEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutEventsEventIdRoute = LayoutEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutAdminPaymentsRoute = LayoutAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsEventIdIndexRoute =
  LayoutEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)
const LayoutEventsEventIdSettingsRoute =
  LayoutEventsEventIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)
const LayoutEventsEventIdInvitationsRoute =
  LayoutEventsEventIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)
const LayoutEventsEventIdAnalyticsRoute =
  LayoutEventsEventIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)
const LayoutEventsEventIdGuestsIndexRoute =
  LayoutEventsEventIdGuestsIndexRouteImport.update({
    id: '/guests/',
    path: '/guests/',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)
const LayoutEventsEventIdGuestsNewRoute =
  LayoutEventsEventIdGuestsNewRouteImport.update({
    id: '/guests/new',
    path: '/guests/new',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistant': typeof LayoutAssistantRoute
  '/billing': typeof LayoutBillingRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/events': typeof LayoutEventsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/templates': typeof LayoutTemplatesRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/admin/payments': typeof LayoutAdminPaymentsRoute
  '/events/$eventId': typeof LayoutEventsEventIdRouteWithChildren
  '/events/new': typeof LayoutEventsNewRoute
  '/events/': typeof LayoutEventsIndexRoute
  '/events/$eventId/analytics': typeof LayoutEventsEventIdAnalyticsRoute
  '/events/$eventId/invitations': typeof LayoutEventsEventIdInvitationsRoute
  '/events/$eventId/settings': typeof LayoutEventsEventIdSettingsRoute
  '/events/$eventId/': typeof LayoutEventsEventIdIndexRoute
  '/events/$eventId/guests/new': typeof LayoutEventsEventIdGuestsNewRoute
  '/events/$eventId/guests/': typeof LayoutEventsEventIdGuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistant': typeof LayoutAssistantRoute
  '/billing': typeof LayoutBillingRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/templates': typeof LayoutTemplatesRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/admin/payments': typeof LayoutAdminPaymentsRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/events': typeof LayoutEventsIndexRoute
  '/events/$eventId/analytics': typeof LayoutEventsEventIdAnalyticsRoute
  '/events/$eventId/invitations': typeof LayoutEventsEventIdInvitationsRoute
  '/events/$eventId/settings': typeof LayoutEventsEventIdSettingsRoute
  '/events/$eventId': typeof LayoutEventsEventIdIndexRoute
  '/events/$eventId/guests/new': typeof LayoutEventsEventIdGuestsNewRoute
  '/events/$eventId/guests': typeof LayoutEventsEventIdGuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/assistant': typeof LayoutAssistantRoute
  '/_layout/billing': typeof LayoutBillingRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/events': typeof LayoutEventsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/templates': typeof LayoutTemplatesRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/_layout/admin/payments': typeof LayoutAdminPaymentsRoute
  '/_layout/events/$eventId': typeof LayoutEventsEventIdRouteWithChildren
  '/_layout/events/new': typeof LayoutEventsNewRoute
  '/_layout/events/': typeof LayoutEventsIndexRoute
  '/_layout/events/$eventId/analytics': typeof LayoutEventsEventIdAnalyticsRoute
  '/_layout/events/$eventId/invitations': typeof LayoutEventsEventIdInvitationsRoute
  '/_layout/events/$eventId/settings': typeof LayoutEventsEventIdSettingsRoute
  '/_layout/events/$eventId/': typeof LayoutEventsEventIdIndexRoute
  '/_layout/events/$eventId/guests/new': typeof LayoutEventsEventIdGuestsNewRoute
  '/_layout/events/$eventId/guests/': typeof LayoutEventsEventIdGuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assistant'
    | '/billing'
    | '/dashboard'
    | '/events'
    | '/settings'
    | '/templates'
    | '/invite/$slug'
    | '/admin/payments'
    | '/events/$eventId'
    | '/events/new'
    | '/events/'
    | '/events/$eventId/analytics'
    | '/events/$eventId/invitations'
    | '/events/$eventId/settings'
    | '/events/$eventId/'
    | '/events/$eventId/guests/new'
    | '/events/$eventId/guests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assistant'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/templates'
    | '/invite/$slug'
    | '/admin/payments'
    | '/events/new'
    | '/events'
    | '/events/$eventId/analytics'
    | '/events/$eventId/invitations'
    | '/events/$eventId/settings'
    | '/events/$eventId'
    | '/events/$eventId/guests/new'
    | '/events/$eventId/guests'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/assistant'
    | '/_layout/billing'
    | '/_layout/dashboard'
    | '/_layout/events'
    | '/_layout/settings'
    | '/_layout/templates'
    | '/invite/$slug'
    | '/_layout/admin/payments'
    | '/_layout/events/$eventId'
    | '/_layout/events/new'
    | '/_layout/events/'
    | '/_layout/events/$eventId/analytics'
    | '/_layout/events/$eventId/invitations'
    | '/_layout/events/$eventId/settings'
    | '/_layout/events/$eventId/'
    | '/_layout/events/$eventId/guests/new'
    | '/_layout/events/$eventId/guests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  InviteSlugRoute: typeof InviteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$slug': {
      id: '/invite/$slug'
      path: '/invite/$slug'
      fullPath: '/invite/$slug'
      preLoaderRoute: typeof InviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/templates': {
      id: '/_layout/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof LayoutTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events': {
      id: '/_layout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof LayoutEventsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/billing': {
      id: '/_layout/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof LayoutBillingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assistant': {
      id: '/_layout/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof LayoutAssistantRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/': {
      id: '/_layout/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof LayoutEventsIndexRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/events/new': {
      id: '/_layout/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof LayoutEventsNewRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/events/$eventId': {
      id: '/_layout/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof LayoutEventsEventIdRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/admin/payments': {
      id: '/_layout/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof LayoutAdminPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/$eventId/': {
      id: '/_layout/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof LayoutEventsEventIdIndexRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
    '/_layout/events/$eventId/settings': {
      id: '/_layout/events/$eventId/settings'
      path: '/settings'
      fullPath: '/events/$eventId/settings'
      preLoaderRoute: typeof LayoutEventsEventIdSettingsRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
    '/_layout/events/$eventId/invitations': {
      id: '/_layout/events/$eventId/invitations'
      path: '/invitations'
      fullPath: '/events/$eventId/invitations'
      preLoaderRoute: typeof LayoutEventsEventIdInvitationsRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
    '/_layout/events/$eventId/analytics': {
      id: '/_layout/events/$eventId/analytics'
      path: '/analytics'
      fullPath: '/events/$eventId/analytics'
      preLoaderRoute: typeof LayoutEventsEventIdAnalyticsRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
    '/_layout/events/$eventId/guests/': {
      id: '/_layout/events/$eventId/guests/'
      path: '/guests'
      fullPath: '/events/$eventId/guests/'
      preLoaderRoute: typeof LayoutEventsEventIdGuestsIndexRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
    '/_layout/events/$eventId/guests/new': {
      id: '/_layout/events/$eventId/guests/new'
      path: '/guests/new'
      fullPath: '/events/$eventId/guests/new'
      preLoaderRoute: typeof LayoutEventsEventIdGuestsNewRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
  }
}

interface LayoutEventsEventIdRouteChildren {
  LayoutEventsEventIdAnalyticsRoute: typeof LayoutEventsEventIdAnalyticsRoute
  LayoutEventsEventIdInvitationsRoute: typeof LayoutEventsEventIdInvitationsRoute
  LayoutEventsEventIdSettingsRoute: typeof LayoutEventsEventIdSettingsRoute
  LayoutEventsEventIdIndexRoute: typeof LayoutEventsEventIdIndexRoute
  LayoutEventsEventIdGuestsNewRoute: typeof LayoutEventsEventIdGuestsNewRoute
  LayoutEventsEventIdGuestsIndexRoute: typeof LayoutEventsEventIdGuestsIndexRoute
}

const LayoutEventsEventIdRouteChildren: LayoutEventsEventIdRouteChildren = {
  LayoutEventsEventIdAnalyticsRoute: LayoutEventsEventIdAnalyticsRoute,
  LayoutEventsEventIdInvitationsRoute: LayoutEventsEventIdInvitationsRoute,
  LayoutEventsEventIdSettingsRoute: LayoutEventsEventIdSettingsRoute,
  LayoutEventsEventIdIndexRoute: LayoutEventsEventIdIndexRoute,
  LayoutEventsEventIdGuestsNewRoute: LayoutEventsEventIdGuestsNewRoute,
  LayoutEventsEventIdGuestsIndexRoute: LayoutEventsEventIdGuestsIndexRoute,
}

const LayoutEventsEventIdRouteWithChildren =
  LayoutEventsEventIdRoute._addFileChildren(LayoutEventsEventIdRouteChildren)

interface LayoutEventsRouteChildren {
  LayoutEventsEventIdRoute: typeof LayoutEventsEventIdRouteWithChildren
  LayoutEventsNewRoute: typeof LayoutEventsNewRoute
  LayoutEventsIndexRoute: typeof LayoutEventsIndexRoute
}

const LayoutEventsRouteChildren: LayoutEventsRouteChildren = {
  LayoutEventsEventIdRoute: LayoutEventsEventIdRouteWithChildren,
  LayoutEventsNewRoute: LayoutEventsNewRoute,
  LayoutEventsIndexRoute: LayoutEventsIndexRoute,
}

const LayoutEventsRouteWithChildren = LayoutEventsRoute._addFileChildren(
  LayoutEventsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAssistantRoute: typeof LayoutAssistantRoute
  LayoutBillingRoute: typeof LayoutBillingRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutEventsRoute: typeof LayoutEventsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutAdminPaymentsRoute: typeof LayoutAdminPaymentsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAssistantRoute: LayoutAssistantRoute,
  LayoutBillingRoute: LayoutBillingRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutEventsRoute: LayoutEventsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutAdminPaymentsRoute: LayoutAdminPaymentsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteSlugRoute: InviteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
